### PR TITLE
Fix Registry Key Evaluation

### PR DESCRIPTION
**Pull request by GavinEke**
Changed all instances of `hklm:` and `hklm:\` with `HKLM:\` to be readable and consistent with other modules and documentation while also fixing Issue #8

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpendingreboot/15)

### CODE REVIEW

**Comment by GavinEke** [comment]
I noticed the failed tests relate to files that I have not changed. Should I be targeting the dev branch or the master branch?

**Comment by johlju** [comment]
@GavinEke You should target the dev branch. This repo haven't merged a PR for soon two years, so the test framework has evolved a lot, and unfortunately this repo don't have a community maintainer that kept the repo up to date, and @kwirkykat and @mbreakey3 are very busy with their regular job. 

Looks like the last merged PR passed the test, but that must be false positive since the test are failing now. 
https://ci.appveyor.com/project/PowerShell/xpendingreboot/build/0.3.46.0

If you are up to resolve this some of these are easy to resolve.

1. Remove any tab characters in the README.md.
  https://ci.appveyor.com/project/PowerShell/xpendingreboot/build/0.3.51.0#L318
1. The file xPendingReboot.tests.ps1 must have a blank row at the end of the file.
  https://ci.appveyor.com/project/PowerShell/xpendingreboot/build/0.3.51.0#L325
1. Pester recently release v4.0 with breaking changes. All `Assert-VerifiableMocks` need to change to `Assert-VerifiableMock` (without the 's' at the end).
  https://ci.appveyor.com/project/PowerShell/xpendingreboot/build/0.3.51.0#L553

These must have always failed (?), but reported as false positive way back in the last PR. I do not know what the problem is with these (haven't looked at the code). 

1. https://ci.appveyor.com/project/PowerShell/xpendingreboot/build/0.3.51.0#L556
1. https://ci.appveyor.com/project/PowerShell/xpendingreboot/build/0.3.51.0#L561

**Comment by GavinEke** [comment]
Thanks @johlju I will have a look into resolving all the failed test tomorrow. I think I should be able to resolve most if not all.

**Comment by GavinEke** [comment]
Fixed tests.

**Comment by johlju** [comment]
Awesome work on this one! Thanks for fixing most PSSA rules! :smile: 

I made a couple of minor review comments.

---

Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 16 at r3](https://reviewable.io:443/reviews/powershell/xpendingreboot/15#-L88Sa70yAEbtSQhQSrx:-L88Sa70yAEbtSQhQSry:bf1d2dj) ([raw file](https://github.com/powershell/xpendingreboot/blob/2ec541e289bdbbde123f6842291815ddbf383400/README.md#L16)):*
> DscResource.Kit

This must be a very old name. The link works, but this should be 'DscResources' instead, do you mind fixing this as well?

---

*[README.md, line 35 at r3](https://reviewable.io:443/reviews/powershell/xpendingreboot/15#-L88T1F4K5xChoCc9Gn6:-L88T1F4K5xChoCc9Gn7:b-7iouny) ([raw file](https://github.com/powershell/xpendingreboot/blob/2ec541e289bdbbde123f6842291815ddbf383400/README.md#L35)):*
> ```Markdown
> * **ComponentBasedServicing**: (Read-only) One of the locations that are examined by the resource.
> 
> Details are returned by Get-DSCConfiguration.
> ```

We should indent this row two spaces and the blank rows before and after should be removed. I think it will be rendered correctly then on the description of `ComponentBasedServicing` parameter.

Now it is rendered wrong I think:
https://github.com/GavinEke/xPendingReboot/blob/2ec541e289bdbbde123f6842291815ddbf383400/README.md#xpendingreboot-1

---

*[DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1, line 78 at r3](https://reviewable.io:443/reviews/powershell/xpendingreboot/15#-L88ULn-ecnvXSbi6j98:-L88ULn-ecnvXSbi6j99:b-5qm6iq) ([raw file](https://github.com/powershell/xpendingreboot/blob/2ec541e289bdbbde123f6842291815ddbf383400/DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1#L78)):*
> ```PowerShell
>     (
>         [Parameter(Mandatory=$true)]
>         [string]$Name,
> ```

Non-blocking, meaning that comment is not part of your change, you may leave as-is. 

If we move variable name to the next row  (under the type) it will align with the style guideline. Throughout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpendingreboot/15#-:-L88UAGqC2LBwYszril6:bdcpgbh)*

**Comment by GavinEke** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 35 at r3](https://reviewable.io:443/reviews/powershell/xpendingreboot/15#-L88T1F4K5xChoCc9Gn6:-L89Yb9hsCRwFWPX_7AK:b-9p0pq2) ([raw file](https://github.com/powershell/xpendingreboot/blob/2ec541e289bdbbde123f6842291815ddbf383400/README.md#L35)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should indent this row two spaces and the blank rows before and after should be removed. I think it will be rendered correctly then on the description of `ComponentBasedServicing` parameter.

Now it is rendered wrong I think:
https://github.com/GavinEke/xPendingReboot/blob/2ec541e289bdbbde123f6842291815ddbf383400/README.md#xpendingreboot-1
</blockquote></details>

I have decided the sentence is redundant and I have removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpendingreboot/15)*

**Comment by GavinEke** [comment]
Thanks for the review Johan. I have made the suggested changes.

---

Reviewed 1 of 2 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xpendingreboot/15#-:-L89Zduy4-1lLmir6Eye:b6p4zwz)*

**Comment by GavinEke** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 16 at r3](https://beta.reviewable.io/reviews/powershell/xpendingreboot/15#-L88Sa70yAEbtSQhQSrx:-L8A4gpKCy1Wkxw6BBTY:b-896fix) ([raw file](https://github.com/powershell/xpendingreboot/blob/2ec541e289bdbbde123f6842291815ddbf383400/README.md#L16)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> DscResource.Kit

This must be a very old name. The link works, but this should be 'DscResources' instead, do you mind fixing this as well?
</blockquote></details>

Done.

---

*[README.md, line 35 at r3](https://beta.reviewable.io/reviews/powershell/xpendingreboot/15#-L88T1F4K5xChoCc9Gn6:-L8A4hhO9-KfUyzDVQoS:b-896fix) ([raw file](https://github.com/powershell/xpendingreboot/blob/2ec541e289bdbbde123f6842291815ddbf383400/README.md#L35)):*
<details><summary><i>Previously, GavinEke (Gavin Eke) wrote…</i></summary><blockquote>

I have decided the sentence is redundant and I have removed it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xpendingreboot/15)*

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 16 at r3](https://reviewable.io:443/reviews/powershell/xpendingreboot/15#-L88Sa70yAEbtSQhQSrx:-L8CZ0Y8-dAmlQLdjJ2x:b-rthac4) ([raw file](https://github.com/powershell/xpendingreboot/blob/2ec541e289bdbbde123f6842291815ddbf383400/README.md#L16)):*
<details><summary><i>Previously, GavinEke (Gavin Eke) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM. For some reason I couldn't resolve this one when I acknowledged. 

---

*[README.md, line 35 at r3](https://reviewable.io:443/reviews/powershell/xpendingreboot/15#-L88T1F4K5xChoCc9Gn6:-L8CZB0eRW_61tNUHm-v:b-a0j8pu) ([raw file](https://github.com/powershell/xpendingreboot/blob/2ec541e289bdbbde123f6842291815ddbf383400/README.md#L35)):*
<details><summary><i>Previously, GavinEke (Gavin Eke) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM. For some reason I couldn't resolve this one when I acknowledged. 

---

*[README.md, line 47 at r4](https://reviewable.io:443/reviews/powershell/xpendingreboot/15#-L8CZz_7xnJxPqbK8L_f:-L8CZz_7xnJxPqbK8L_g:b-8x5zkb) ([raw file](https://github.com/powershell/xpendingreboot/blob/3be3f06e00fdd71e70f5e0ce0d8d98a08cb890f5/README.md#L47)):*
> ```Markdown
> ### Unreleased
> 
> * Converted appveyor.yml to install Pester from PSGallery instead of from Chocolatey.
> ```

Could you please add an entry to what was chnage in this PR? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpendingreboot/15)*

**Comment by GavinEke** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 47 at r4](https://beta.reviewable.io/reviews/powershell/xpendingreboot/15#-L8CZz_7xnJxPqbK8L_f:-L8EmHiK3ZiKk5edYfrQ:b-896fix) ([raw file](https://github.com/powershell/xpendingreboot/blob/3be3f06e00fdd71e70f5e0ce0d8d98a08cb890f5/README.md#L47)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could you please add an entry to what was chnage in this PR? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xpendingreboot/15)*

**Comment by johlju** [comment]
:lgtm:

@kwirkykat would you mind merging this change. @GavinEke was kind enough to help us clean up this repo so it passes the tests, so would be great to have this PR merged.

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 47 at r4](https://reviewable.io:443/reviews/powershell/xpendingreboot/15#-L8CZz_7xnJxPqbK8L_f:-L8G2T_LQ2WIRNBUyKOi:b1z0rvu) ([raw file](https://github.com/powershell/xpendingreboot/blob/3be3f06e00fdd71e70f5e0ce0d8d98a08cb890f5/README.md#L47)):*
<details><summary><i>Previously, GavinEke (Gavin Eke) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM. This comment was not resolved when I acknowledge for some reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xpendingreboot/15#-:-L8G2aYd1qckEMsDrNzX:bymqxmq)*

**Comment by GamerLivingWill** [comment]
Thank you @kwirkykat !

**Pull request merged**
