### PR TITLE
xPendingReboot: fix for resource not detecting a pending reboot after domain join

### PR DESCRIPTION
**Pull request by peppekerstens**
xPendingReboot resource was not detecting a pending reboot after domain join

used code from https://gallery.technet.microsoft.com/scriptcenter/Get-PendingReboot to correct this behavior

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xpendingreboot/10)

### CODE REVIEW

**Comment by kwirkykat** [comment]
@peppekerstens Please update your PR title per [this section](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#pull-request-title) of our contributing document.

**Comment by narrieta** [comment]
@peppekerstens : would you double-check this submission matches the issue in the description? I updated the title to match the description, but the changes in this PR seem unrelated.

Thanks

**Comment by peppekerstens** [comment]
@kwirkykat: I will do that. this is my first admission. please bear with me :)  

@narrieta: to elaborate on this issue further; you are able to re-produce this issue by 
(1) adding a machine to the domain without rebooting. Either by doing it manually or by issuing the DSC resource for it without changing the default local DSC manager settings on a Windows Server. The server will not reboot.
(2) issuing current master branch of xpendingreboot and request/config a reboot on current state; it wil NOT detect a pending reboot
(3) apply a config change to the local DSC manager settings and set -> RebootNodeIfNeeded = $true  
(4) after applying my fix it _will_ reboot :)
(5) furthermore; the xComputer resource in module xComputermanagement does not detect the pending reboot either when de the local DSCmanager settings are being changed  to 'RebootNodeIfNeeded = $true' after a first 'run with default DSC settings' (without  manual reboot). But this is an issue for another DSC resource/module :)

(tested on Win2016 RTM EVAL)

We could argue endlessly if this would happen in "real world" settings; probably 99% of the time a 'smart' DevOps person would set the  'RebootNodeIfNeeded = $true' first :) and there would be no issue, even on (5).
But true to DSC rules; the above behavior is NOT idempotent...

**Comment by peppekerstens** [comment]
If I need to do anything to further prove my issue and/or any steps I need to follow; please tell me. I'm new to this :)

RTFM is fine. Links to M are preferable :) :)

**Comment by mgreenegit** [comment]
Were the original changes for this PR lost somehow?  I am not seeing the functional changes described actually implemented in the dsc resource.

**Comment by peppekerstens** [comment]
@mgreenegit 
Dunno what happened; the repo is missing in my GitHub environment...(?)

I still have a local copy of the changes. What to do? New branche & re-submit merge request?

code change is very simple (in MSFT_xPendingReboot.psm1);

......

$PendingComputerName = (Get-ItemProperty 'hklm:\SYSTEM\CurrentControlSet\Control\ComputerName\ComputerName').ComputerName

```
## Query JoinDomain key from the registry - These keys are present if pending a reboot from a domain join operation
$Netlogon = (Get-ChildItem 'hklm:\SYSTEM\CurrentControlSet\Services\Netlogon').PSChildName
$PendDomJoin = ($Netlogon -contains 'JoinDomain') -or ($Netlogon -contains 'AvoidSpnSet')

$PendingComputerRename = ($ActiveComputerName -ne $PendingComputerName) -or $PendDomJoin
```

......

**Comment by mgreenegit** [comment]
Can you clone the PR locally and add a new commit with the change?

https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by kwirkykat** [comment]
@peppekerstens You need to change the base and target of this PR. Right this PR is trying to merge the PowerShell repo's dev branch into the PowerShell repo's master branch. You want it to be merging your fork's branch into the PowerShell repo's dev branch.

**Comment by kwirkykat** [comment]
@peppekerstens You can either try to fix it in this PR or open a new PR if you would like

**Comment by kwirkykat** [comment]
@peppekerstens Closing this PR as it has not had response in a while and it is now blocking release of this module due to the incorrect base and target branches

**Pull request closed without merging**
