### PR TITLE
Script analyzer and formatting fixes fixes

### PR DESCRIPTION
**Pull request by Chirishman**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpendingreboot/19)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/xpendingreboot/19)* status: all files reviewed, 5 unresolved discussions (waiting on @Chirishman)

___
*[.gitignore, line 1 at r2](https://reviewable.io/reviews/powershell/xpendingreboot/19#-LIf76v0305qqZHQaIO9:-LIf76v0305qqZHQaIOA:b-uvlwh6) ([raw file](https://github.com/powershell/xpendingreboot/blob/a4f59c5f6feb7c5adf8ec2eb7ec1729947b03507/.gitignore#L1)):*
> ```
> .vs/ProjectSettings.json
> ```

Please change the .gitignore file to just include

```
.vs
.vscode
```
___
*[DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1, line 16 at r2](https://reviewable.io/reviews/powershell/xpendingreboot/19#-LIf7RjD8lBozzl1f0q6:-LIf7RjD8lBozzl1f0q7:b-qbtm9b) ([raw file](https://github.com/powershell/xpendingreboot/blob/a4f59c5f6feb7c5adf8ec2eb7ec1729947b03507/DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1#L16)):*
> ```PowerShell
> 
>     $ComponentBasedServicingKeys = (Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\').Name
>     if ($ComponentBasedServicingKeys) {
> ```

Open brace should be on a separate row. 
https://ci.appveyor.com/project/PowerShell/xpendingreboot/build/0.3.66.0#L1337

You could add the workspace settings file for VSCode here, and commit it to this PR;
https://github.com/PowerShell/DscResources/tree/master/DscResource.Template/.vscode
___
*[DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1, line 67 at r2](https://reviewable.io/reviews/powershell/xpendingreboot/19#-LIf7u1T7ODno0On4lo8:-LIf7u1T7ODno0On4lo9:b-d9us81) ([raw file](https://github.com/powershell/xpendingreboot/blob/a4f59c5f6feb7c5adf8ec2eb7ec1729947b03507/DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1#L67)):*
> ```
> SupportsShouldProcess
> ```

We should not use `SupportsShouldProcess` for DSC Resources since DSC resources does not support that.
___
*[DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1, line 94 at r2](https://reviewable.io/reviews/powershell/xpendingreboot/19#-LIf8MF12FmmjVi-Z216:-LIf8MF12FmmjVi-Z217:byzpyxt) ([raw file](https://github.com/powershell/xpendingreboot/blob/a4f59c5f6feb7c5adf8ec2eb7ec1729947b03507/DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1#L94)):*
> ```
> Set-Variable -Name DSCMachineStatus -Scope Global -Value 1
> ```

Please keep `$global:DSCMachineStatus = 1` as that is the most described way of specifying the this variable. 
___
*[DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1, line 155 at r2](https://reviewable.io/reviews/powershell/xpendingreboot/19#-LIf8xht2i1sOw3vGkM-:-LIf8xht2i1sOw3vGkM0:b-e4nw8) ([raw file](https://github.com/powershell/xpendingreboot/blob/a4f59c5f6feb7c5adf8ec2eb7ec1729947b03507/DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1#L155)):*
> ```PowerShell
> Export-ModuleMember -Function *-TargetResource
> 
> Remove-Variable -Name regRebootLocations -ErrorAction Ignore
> ```

`regRebootLocations` is not set anywhere, so do we need this?

**Comment by johlju** [comment]
@Chirishman Thanks for fixing style issues! Just a few review comments. 🙂

**Comment by PlagueHO** [comment]
@johlju - regarding the comment regarding `regRebootLocations` - I had the exact same thought as you when I encountered it. It seems to go back right to the very first commit of this resource. The purpose is a bit of a mystery. Perhaps @joeyaiello can shed some light on the purpose? If not, I'm going to delete it as part of the migration to ComputerManagementDsc.

**Review by Chirishman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/xpendingreboot/19)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @Chirishman and @johlju)

___
*[DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1, line 16 at r2](https://reviewable.io/reviews/powershell/xpendingreboot/19#-LIf7RjD8lBozzl1f0q6:-Lm646Mp6t-PMyBESewN:bpb9aqp) ([raw file](https://github.com/powershell/xpendingreboot/blob/a4f59c5f6feb7c5adf8ec2eb7ec1729947b03507/DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1#L16)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Open brace should be on a separate row. 
https://ci.appveyor.com/project/PowerShell/xpendingreboot/build/0.3.66.0#L1337

You could add the workspace settings file for VSCode here, and commit it to this PR;
https://github.com/PowerShell/DscResources/tree/master/DscResource.Template/.vscode
</blockquote></details>

Done. I hate curly braces on newlines but it's done.
___
*[DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1, line 67 at r2](https://reviewable.io/reviews/powershell/xpendingreboot/19#-LIf7u1T7ODno0On4lo8:-Lm64gaHBHf1vyjuZ10Z:b440avb) ([raw file](https://github.com/powershell/xpendingreboot/blob/a4f59c5f6feb7c5adf8ec2eb7ec1729947b03507/DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1#L67)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> SupportsShouldProcess
> ```

We should not use `SupportsShouldProcess` for DSC Resources since DSC resources does not support that.
</blockquote></details>

If SupportsShouldProcess is not to be used here then please update the [official examples](https://docs.microsoft.com/en-us/powershell/dsc/resources/singleinstance) from docs.microsoft.com
___
*[DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1, line 94 at r2](https://reviewable.io/reviews/powershell/xpendingreboot/19#-LIf8MF12FmmjVi-Z216:-Lm65ElR7rH_mYQwV5X9:b-896fix) ([raw file](https://github.com/powershell/xpendingreboot/blob/a4f59c5f6feb7c5adf8ec2eb7ec1729947b03507/DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1#L94)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Set-Variable -Name DSCMachineStatus -Scope Global -Value 1
> ```

Please keep `$global:DSCMachineStatus = 1` as that is the most described way of specifying the this variable. 

</blockquote></details>

Done.
___
*[DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1, line 155 at r2](https://reviewable.io/reviews/powershell/xpendingreboot/19#-LIf8xht2i1sOw3vGkM-:-Lm65JVt9J1MK7Qq1-RT:b-ogwyvh) ([raw file](https://github.com/powershell/xpendingreboot/blob/a4f59c5f6feb7c5adf8ec2eb7ec1729947b03507/DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1#L155)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

`regRebootLocations` is not set anywhere, so do we need this?
</blockquote></details>

As noted, it's from the original. I don't know the logic behind it so I left it.

**Review by Chirishman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/xpendingreboot/19)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @Chirishman and @johlju)

___
*[DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1, line 16 at r2](https://reviewable.io/reviews/powershell/xpendingreboot/19#-LIf7RjD8lBozzl1f0q6:-Lm65ZpD6MujPTmB-a2g:b-896fix) ([raw file](https://github.com/powershell/xpendingreboot/blob/a4f59c5f6feb7c5adf8ec2eb7ec1729947b03507/DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1#L16)):*
<details><summary><i>Previously, Chirishman wrote…</i></summary><blockquote>

Done. I hate curly braces on newlines but it's done.
</blockquote></details>

Done.

**Review by Chirishman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/xpendingreboot/19)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @johlju)

___
*[.gitignore, line 1 at r2](https://reviewable.io/reviews/powershell/xpendingreboot/19#-LIf76v0305qqZHQaIO9:-Lm6Ah5xB7SiDzC_dkFd:b-896fix) ([raw file](https://github.com/powershell/xpendingreboot/blob/a4f59c5f6feb7c5adf8ec2eb7ec1729947b03507/.gitignore#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please change the .gitignore file to just include

```
.vs
.vscode
```

</blockquote></details>

Done.

**Comment by PlagueHO** [comment]
Hi @Chirishman - this resource is actually being migrated into ComputerManagementDsc and updated to meet HQRM at the same time. So there might not be too much need to continue this PR. Sorry, I missed this work being done so didn't alert you earlier - it was being discussed in one of the other issues in this repo.

**Review by johlju — COMMENTED** [review]
@Chirishman Thank you for your contribution, but since this PR only suggest style changes, and the PR moving this resource will include these and more, I see no point merging this PR. This resource will be deprecated in the next release.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/xpendingreboot/19#-:-LmAePGQ0nYf4tAzdgwf:b2qwohs)* status: all files reviewed, 1 unresolved discussion (waiting on @Chirishman)

___
*[DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1, line 67 at r2](https://reviewable.io/reviews/powershell/xpendingreboot/19#-LIf7u1T7ODno0On4lo8:-LmAdVxX7KXoCIdfWmxG:b-clx73s) ([raw file](https://github.com/powershell/xpendingreboot/blob/a4f59c5f6feb7c5adf8ec2eb7ec1729947b03507/DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1#L67)):*
<details><summary><i>Previously, Chirishman wrote…</i></summary><blockquote>

If SupportsShouldProcess is not to be used here then please update the [official examples](https://docs.microsoft.com/en-us/powershell/dsc/resources/singleinstance) from docs.microsoft.com
</blockquote></details>

That article is best practice for single instance, not best practice for the code. It is referencing some very old code, new code is here https://github.com/PowerShell/ComputerManagementDsc/blob/dev/DSCResources/MSFT_TimeZone/MSFT_TimeZone.psm1

I sent in a PR proposing to resolve the article (we can change doc on our own now :slightly_smiling_face:) https://github.com/MicrosoftDocs/PowerShell-Docs/pull/4638

**Comment by gaelcolas** [comment]
As per @johlju point, I'm going to close this one and wait for the merge to CptMgtDsc.
Thanks!

**Pull request closed without merging**
