### PR TITLE
Update example text in readme

### PR DESCRIPTION
**Pull request by kjacobsen**
The second example didn't actually do anything with hotfixes, so removed the confusing text.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpendingreboot/11)

### CODE REVIEW

**Comment by kjacobsen** [comment]
Noticed this one didn't pass build. I have cleaned up the whitespace and more importantly found the tab that broke the build.

**Comment by johlju** [comment]
@kjacobsen Sorry for the long delay in response on you pull request. Are you still able to work on this one? If so I want to help you get this merged,

**Comment by kjacobsen** [comment]
Happy to work on getting this one merged in. Let me know what needs to be done.

**Comment by johlju** [comment]
Awesome! We need to rebase this PR first, since there are merge conflicts. Do you know how to do that? If not, I give you a link here, but if you get stuck, just comment here and I will help.  Here is the link https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

**Comment by johlju** [comment]
Labeling this PR as abandoned since it has gone 14 days or more since the last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by kjacobsen** [comment]
Hi,

This PR is ready for merge. Can it be reviewed and merged?

**Comment by kjacobsen** [comment]
@johlju what do we need to do to get this merged?

**Review by gaelcolas — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/xpendingreboot/11)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by gaelcolas** [comment]
Done.

Just needed some time @kjacobsen  ;)
@johlju is doing tons, feel free to hit me up if things are taking too long.
I'm going through the backlog of PRs waiting.

**Pull request merged**
